name: Test

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
    - run: uv tool run black dags/
    - uses: micael-grilo/airflow-dags-test-action@v2.10.3
