name: Test

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
    - run: uvx black . --check --diff --color
    - run: make requirements.txt
    - uses: jayamanikharyono/airflow-dag-action@v2.3
      with:
        accessToken: ${{ secrets.GITHUB_TOKEN }}